# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
encoding: utf-8

title: A System for Vital Signs Self-Measurement
email: vitalsigncenter@gamil.com
description: >- 
  The patients can take thier daily vital signs measurement 
  and send it to medical assistants to keep track of 
  patientsâ€™ conditions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.vitalsignapp.com"
# twitter_username: jekyllrb
github_username:  vitalsignapp

# Build settings
markdown: kramdown
# theme: minima

# destination: _site

plugins:
  - jekyll-multiple-languages-plugin
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap  

# exclude_from_localizations: ["js", "images", "css", "fonts"]
languages: ["th", "en"]

sass:
  sass_dir: ./css

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
